config/routes.rb
CsfTaskManager::Application.routes.draw do
  devise_for :users, :controllers => { :sessions => "authentications" }
  resource :user
  root :to => 'main#index'
  match "/api/auth" => "main#auth"
  
  resources :goals do
    resources :exclusions
  end
  resources :roles
end

app/models/exclusion.rb
# == Schema Information
#
# Table name: exclusions
#
#  id         :integer(4)      not null, primary key
#  goal_id    :integer(4)
#  date       :datetime
#  created_at :datetime
#  updated_at :datetime
#

class Exclusion < ActiveRecord::Base
  ## included modules & attr_*
  
  ## associations
  belongs_to :goal
  
  ## plugins

  ## callbacks

  ## validations
  validates :date, :presence => true

  ## named_scopes

  ## class methods
  public
  protected
  private
end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id              :integer(4)      not null, primary key
#  user_id         :integer(4)
#  title           :string(255)
#  note            :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  role_id         :integer(4)
#  date            :datetime
#  repeat_schedule :string(255)
#  weekday         :integer(4)
#  priority        :string(255)
#

class Goal < ActiveRecord::Base
  ## included modules & attr_*
  
  ## associations
  belongs_to :user
  belongs_to :role
  has_many :exclusions
  
  ## plugins

  ## callbacks
  before_save :set_weekday

  ## validations
  validates :title, :user_id, :date, :priority, :repeat_schedule, :presence => true

  ## named_scopes
  scope :this_week, lambda { |week_start, week_end| where("(date >= ? AND date <= ?) OR repeat_schedule = ? OR repeat_schedule = ?", week_start, week_end, 'weekly', 'monthly') }
  scope :this_day, lambda { |day| where("date >= ? AND date <= ?", day.beginning_of_day, day.end_of_day) }
  scope :this_month, lambda { |day| where("date >= ? AND date <= ?", day.beginning_of_month, day.end_of_month) }
  scope :week_priority, where("priority = 'week'")
  scope :day_priority, where("priority = 'day'")

  ## class methods
  public

  # def as_json(options = {}) 
  #   super(options.merge(include: { exclusions: { only: [:date, :goal_id] } }))
  # end
  
  protected
  private
  
  def set_weekday
    self.weekday = date.wday
  end
end

app/models/role.rb
# == Schema Information
#
# Table name: roles
#
#  id          :integer(4)      not null, primary key
#  user_id     :integer(4)
#  name        :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Role < ActiveRecord::Base
  ## included modules & attr_*

  ## associations
  belongs_to :user
  has_many :goals
  
  ## plugins

  ## callbacks

  ## validations

  ## named_scopes

  ## class methods
  public
  protected
  private
  
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer(4)      not null, primary key
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(128)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer(4)      default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  ## included modules & attr_*

  ## associations
  has_many :goals
  has_many :roles

  ## plugins

  ## callbacks

  ## validations

  ## named_scopes

  ## class methods
  public
  protected
  private
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery
end

app/controllers/authentications_controller.rb
class AuthenticationsController < Devise::SessionsController
  
  # Custom authentication for mobile apps
  def create
    respond_to do |format|
      format.json { 
        user = User.find_by_email(params[:email])
        if user.valid_password?(params[:password])
          sign_in(user)
          render :json => session.to_json 
        end
      }
      format.html { super }
    end
  end
  
end

app/controllers/exclusions_controller.rb
class ExclusionsController < ApplicationController
  before_filter :preload_goal
  
  def create
    ex = @goal.exclusions.create!(params[:exclusion])
    render :json => ex.to_json
  end
  
  def update
    ex = @goal.exclusions.find(params[:exclusion][:id])
    ex.update_attributes(params[:exclusion])
    render :json => ex.to_json
  end
  
  def destroy
    @goal.exclusions.find(params[:id]).destroy
    render :nothing => true
  end
  
  private
  
  def preload_goal
    @goal = Goal.find(params[:goal_id])
    unless current_user == @goal.user
      raise "Access Denied"
    end
  end
  
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def create    
    params[:goal][:date] = params[:goal][:date].to_datetime    
    current_user.goals.create!(params[:goal])
    render :json => current_user.goals.last.to_json
  end
  
  def update
    @goal = Goal.find(params[:goal][:id])
    if @goal.user == current_user
      @goal.update_attributes(params[:goal])
    end
    render :json => @goal.to_json
  end
  
  def index
    render :json => current_user.goals.to_json
  end
  
  def destroy
    goal = Goal.find(params[:id])    
    if current_user == goal.user
      goal.destroy
    end
    render :nothing => true
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_filter :authenticate_user!, :except => [:auth]
  
  def index
    @week_start, @week_end = Time.now.beginning_of_week, Time.now.end_of_week

    @roles = current_user.roles
    @this_week_goals = current_user.goals.this_week(@week_start, @week_end)
    @month_tasks = current_user.goals.map { |goal| {:title => goal.title, :start => goal.date.strftime('%Y-%m-%d')} }
  end
  
  def auth
    username = params[:username]
    user = User.find_by_email(username)
    if sign_in(user)
      render :json => session.to_json
    end
  end    
  
  private
  
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  
  def create
    current_user.roles.create(params[:role])
    render :json => current_user.roles.last.to_json
  end
  
  def update
    
  end
  
  def destroy
    
  end
  
  def index
    render :json => current_user.roles.to_json
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/exclusions_helper.rb
module ExclusionsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/authentications/new.html.erb
<div class="auth-form">
	<h2>Sign in</h2>
	<div class="form-stacked">
		<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
		  <div><%= f.label :email %><br />
		  <%= f.email_field :email %></div>

		  <div><%= f.label :password %><br />
		  <%= f.password_field :password %></div>

		  <% if devise_mapping.rememberable? -%>
		    <div><%= f.label :remember_me %><%= f.check_box :remember_me %> </div>
		  <% end -%>

		  <div><%= f.submit "Sign in", :class => "btn" %></div>
		<% end %>

		<%= render :partial => "devise/shared/links" %>
	</div>
</div>

app/views/exclusions/_form.html.haml
%h3.new
  Add schedule exclusion
.form-stacked
  = form_for Goal.new do |f|
    %p.datepicker
      = f.label :date, :class => "datepicker__label"
      = f.date_select :date, :prefix => :exclusion, :order => [:day, :month, :year], :use_month_numbers => true
%p
  %button.add-exclusion.btn
    Apply
  %h3
    Exclusions list
  %table.exclusions-list{:style => "width: 300px;"}
    %tr
      %td
        No exclusions

app/views/goals/_form.html.haml
%table{:style => "border: none;"}
  %tr
    %td
      .goal-form
        %h3.new
          New Goal
        %h3.edit.hidden
          Edit
        .form-stacked
          = form_for Goal.new do |f|
            %p
              = f.label :title
              = f.text_field :title, :class => "goal-title"
            %p
              = f.label :role
              = f.collection_select(:role_id, @roles, :id, :name)
            %p
              = f.label :note
              = f.text_field :note, :class => "goal-note"
            %p
              = f.label :priority
              = f.select :priority, options_for_select([['Week priority', 'week'], ['Day priority', 'day']])
            %p
              = f.label :repeat_schedule
              = f.select :repeat_schedule, options_for_select([['Daily', 'daily'], ['Weekly', 'weekly'], ['Monthly', 'monthly'], ['None', 'none']])
            %p.datepicker
              = f.label :date, :class => "datepicker__label"
              = f.date_select :date, :prefix => :goal, :order => [:day, :month, :year], :use_month_numbers => true
        %p
          %button.add-goal.btn
            Apply
        %p
          %button.edit-goal.btn.hidden
            Edit
        %p
          %button.delete-goal.btn.hidden.danger
            Delete

    %td
      .exclusion-form
        = render :partial => "exclusions/form"

app/views/layouts/application.html.haml
!!!
%html
  %head
    = javascript_include_tag :application
    = stylesheet_link_tag :application
    = csrf_meta_tags

%body
  .topbar
    .topbar-inner
      .container-fluid
        = link_to "Do it later", root_path, :class => "brand"
        = render :partial => "main/menu"
  - if user_signed_in?
    .container-fluid
      .sidebar
        = render :partial => "main/weekly_roles_goals"
      .content
        .b-notifications
          .alert-message.success{:style => "display: none;"}
            = link_to "x", "#", :class => "close"
            %p
              %strong.title
              %span.body
        = yield
        %footer
  - else
    .content
      = yield
      %footer
    

app/views/main/_daily_priorities.html.haml
.b-day-priorities
  %h3
    Day priorities
  %table{"data-start" => @week_start.strftime('%m.%d.%Y'), "data-end" => @week_end.strftime('%m.%d.%Y')}

    %tr
      - @week_start.to_date.upto(@week_end.to_date) do |date|
        %th
          = date.strftime('%A, %d.%m.%Y')
    %tr
      - @week_start.to_date.upto(@week_end.to_date) do |date|
        %td{:class => "wday-#{date.wday}", "data-date" => date}

app/views/main/_menu.html.haml
%ul.nav
  - if user_signed_in?
    %li
      = link_to "Calendar", "/#!/"
    %li.dropdown
      = link_to "Add", "#", :class => "dropdown-toggle"
      %ul.dropdown-menu
        %li
          = link_to "Goal", "#!/goal/"
        %li
          = link_to "Role", "#!/role/"
    %li
      = link_to "Settings", "#"
%p.pull-right
  - if user_signed_in?
    Logged in as
    = link_to current_user.email, user_path
    = "/"
    = link_to "Exit", destroy_user_session_path, :method => :delete, :id => "exit"
  - else
    = link_to "Sign in", new_user_session_path

app/views/main/_week_priorities.html.haml
%h3
  Week priorities
%table
  %tr
    %td.b-weekly-priorities
      - @this_week_goals.each do |goal|
        .b-weekly-role-goals__goal
          = link_to goal[:title], "#!/goal/#{goal[:id]}"
  

app/views/main/_weekly_roles_goals.html.haml
%h3
  Roles And Goals
- if !@roles.count.zero?
  %table.bordered-table.b-weekly-role-goals
    %th
      Roles
    %th
      Goals
    - @roles.each do |role|
      %tr{:class => "role-#{role.id}"}
        %td.role_name
          = role.name
        %td.role_goals
- else
  You don't have any roles yet
  %p
    = link_to "Add one?", "#!/role/"

app/views/main/index.html.haml
:erb
  <script>
    $(document).ready(function(){
      CsfTaskManager.init(<%= @roles.to_json %>, <%= @this_week_goals.to_json(:include => :exclusions) %>);
      $('#calendar').fullCalendar({
        header: {
          left: 'prev,next today',
          center: 'title'
        },
        editable: true,
        firstDay: 1,
        events: <%= @month_tasks.to_json %> 
      });
    });		    
  </script>
#app
  .app-screen#goal-form.hidden
    = render :partial => "goals/form"

  %table.app-screen.bordered-table#calendar-grid.no-border
    %tr
      %td.no-border{:colspan => 2}
        = render :partial => "daily_priorities"
    %tr
      %td.no-border{:width => "200px"}
        = render :partial => "week_priorities"
      %td.no-border
        #calendar

  .app-screen#role-form.hidden
    = render :partial => "roles/form"

app/views/roles/_form.html.haml
%h3
	New User Role
.form-stacked
	= form_for Role.new do |f|
		= f.label :title
		%p
		= f.text_field :name, :class => "role-title"
		%p
		= f.label :note
		%p
		= f.text_field :description, :class => "role-note"
%p
	%button{:class => "add-role btn"}
		Add